### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by dennisofficial** [responsively-org/responsively-app#1031]
# 🐞 bug report
![image](https://github.com/responsively-org/responsively-app/assets/34203433/43cded42-0ff1-451a-b072-847d38ceebc3)

### ✍️ Description

When downloading from the website, windows gives me this error. I downloaded via `winget` and everything is fine.

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by manojVivek** [comment]
@dennisofficial You're seeing this because the app is not signed with an EV certificate as they are too pricey (costs ~$400/year). 

We won't be able to do much about this. So, I believe you'll have to allow it to explicitly run on Defender to use the app. 

Please re-open if you face any other issues while using the app.
