### ISSUE TITLE
Add a light theme for the App Interface and have a switch in the preferences. 

### ISSUE THREAD

**Issue by saltcod** [responsively-org/responsively-app#238]
Hey guys! Just discovered this and it looks amazing! 

Sadly, my eyes prevent me from being able to work against a dark backgrounds, so I was keen to see if there was a Light mode. The Switch Color Scheme button doesn't seem to do anything when I click it — should that toggle the whole app from light to dark?

Thanks and fantastic work!

**Comment by jjavierdguezas** [comment]
hi @saltcod , 
I think that Switch Color Scheme feature is for the devices view, not for `Responsively App` windows, for example go to https://nandovieira.com/supporting-dark-mode-in-web-content and click the switch button (you will notice the change, because that website handle OS color scheme)

![darkmode2](https://user-images.githubusercontent.com/13673443/86370676-52404180-bc80-11ea-901b-77333af1baed.gif)

what OS are you using?
In Windows I notice that also the Application Menu changes.. 

Maybe you want a Light theme feature 
cc: @manojVivek

**Comment by saltcod** [comment]
aaah I see.   Yeah it seems I do have a feature request then =)

**Comment by manojVivek** [comment]
@jjavierdguezas Yeah that is right, we need to add a light theme for app.

@saltcod Thanks for reporting. We will add this to the roadmap.

**Comment by Grafikart** [comment]
@manojVivek Where would you put this setting ? I could take a look at it (I would put the setting in the setting sidebar to avoid an extra button close to the address bar).

**Comment by manojVivek** [comment]
Yes @Grafikart that is what I was thinking too. 
To add a toggle in `UserPreferences` component - https://github.com/manojVivek/responsively-app/blob/18fdd56e7c8f2686bcc2abfe9871b14ddb450a8e/desktop-app/app/components/UserPreferences/index.js

**Comment by manojVivek** [comment]
Do you want me to assign this to you?

**Comment by Grafikart** [comment]
I thought it would be simple but changing the createMuiTheme type to "light" doesn't seem to work so I'm not sur I will have the time if it's more complex.

**Comment by manojVivek** [comment]
Yes, I understand. Thanks for checking 👍

**Comment by saltcod** [comment]
Been meaning to come by for a few weeks and say THANK YOU for releasing the light version of this! I love it — fantastic work!!
