### ISSUE TITLE
Screenshot > Fixed footer is missing from screenshots

### ISSUE THREAD

**Issue by sebasrodriguez** [responsively-org/responsively-app#297]
Description:

When taking out pictures for any resolution on a page that contains a fixed footer the footer is missing from the final picture.

I've noticed that as soon as it starts to take the pictures the footer is removed and only added back again once all the pictures are taken.

**Comment by manojVivek** [comment]
@sebasrodriguez Yes, we remove all the `fixed` position elements when we try to take a screenshot. 

Since only visible sections can be captured, for longer pages we take multiple screenshots at different scroll positions and then stitch them all together to form the full page screenshot. 
In this process, if the `fixed` position elements are not hidden, it will be captured at each of the intermediate screenshots, and in the final stitched image will have multiple footers. So to avoid that we remove the `fixed` position elements during screenshots.

I hope, I explained it well. `fixed` position elements are tricky in full-page screenshots, but we have plans to revamp the screenshots to use an alternative way that should help solve this.

**Comment by manojVivek** [comment]
Created issue #385 to add an option to make this hiding configurable. 

Closing this one, please watch for the updates there.
