### ISSUE TITLE
Zen Mode 

### ISSUE THREAD

**Issue by steveyang331** [responsively-org/responsively-app#455]
![image](https://user-images.githubusercontent.com/16850883/93347087-43246500-f867-11ea-8d75-c7eb25986b6b.png)

I know currently it can get similar style, not not quite enough mini .

**Comment by jjavierdguezas** [comment]
Like  a 'Zen Mode' or 'Focus Mode' where we only show devices in focus mode (tabs) and hide everything else?
@manojVivek @jzabala what do you think?

**Comment by steveyang331** [comment]
That's right . Zen mode.

**Comment by manojVivek** [comment]
@jjavierdguezas Instead of a specific mode for this, I would suggest adding buttons to hide the top and sidebars. This way it will be more flexible and can be used for other situations too. A quick mockup below:

![Toolbar-hide-buttons](https://user-images.githubusercontent.com/1283424/93694399-fc659200-fb28-11ea-807e-f3f64731553e.png)


What do you guys think?

**Comment by steveyang331** [comment]
Good idea .

**Comment by sidthesloth92** [comment]
@manojVivek  @jjavierdguezas  Can I work on this one?

**Comment by jjavierdguezas** [comment]
Great @sidthesloth92 , I assigned it to you
Thanks!

**Comment by sidthesloth92** [comment]
Update on the issue, have managed to get the primary functionality done. @manojVivek You happen to have the arrow icons from your mock screenshot?

**Comment by manojVivek** [comment]
@sidthesloth92 Can you try this:
```
<svg width="19" height="8" viewBox="0 0 19 8" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1 6.5L9.5 2L18 6.5" stroke="white" stroke-width="2" stroke-linecap="round"/>
</svg>
```

**Comment by sidthesloth92** [comment]
Thanks @manojVivek ..:D
