### ISSUE TITLE
Detachable devtools (multiple windows)

### ISSUE THREAD

**Issue by iBobik** [responsively-org/responsively-app#524]
# 🚀 Feature Request

### 📝 Description

To support multiple displays it sould be able to detach devtools to separate window (like other browsers can), so I can have devtools on one display and browsers on another.

### ✨ Describe the solution you'd like

Add icon to detach devtools next to orientation switch.

Example from Safari:
<img width="141" alt="Snímek obrazovky 2020-10-28 v 18 34 55" src="https://user-images.githubusercontent.com/614232/97474335-4b82bc00-194c-11eb-9889-2ceaf997a54c.png">

### ✍️ Describe alternatives you've considered

Buy bigger display :-(

**Comment by manojVivek** [comment]
@iBobik We already have a way to do this in the user preferences. 

Docking and un-docking implementation is kind of tricky right now, so we have kept this as a user preference option instead of an icon on the dev tools. 

<img width="363" alt="Screenshot 2020-10-29 at 7 51 49 AM" src="https://user-images.githubusercontent.com/1283424/97517832-fbdbd900-19bb-11eb-8235-3e19d4408e9e.png">

**Comment by manojVivek** [comment]
@iBobik Please close this issue if this satisfies your use-case.

**Comment by iBobik** [comment]
Nice, thank you.
