### ISSUE TITLE
Desktop Vertical- and Horizontal Scrollbar also on Non-Desktop-devices

### ISSUE THREAD

**Issue by 123Peter789** [responsively-org/responsively-app#86]
First: "Responsively" is a great idea. 

**Issue: Normal desktop scrollbars are also on non-desktop devices**

**Comment by manojVivek** [comment]
@123Peter789 Can you please add a screenshot explaining the issue?

**Comment by 123Peter789** [comment]
Sure, hope that helps


![image](https://user-images.githubusercontent.com/16413100/82543832-40ab4a80-9ba8-11ea-9c2a-087196f7cbfd.png)

![image](https://user-images.githubusercontent.com/16413100/82543874-5456b100-9ba8-11ea-832c-63176e58bb4a.png)

![image](https://user-images.githubusercontent.com/16413100/82543888-5b7dbf00-9ba8-11ea-9290-fe07504e85d1.png)

**Comment by jjavierdguezas** [comment]
@123Peter789 @manojVivek  @jzabala can you reproduce this issue in the current release? I can't
>Version: 0.11.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/13673443/91216592-841cd400-e716-11ea-811e-fcaaadf15f20.png)

**Comment by jzabala** [comment]
@jjavierdguezas I can't either but this was probably fixed by https://github.com/responsively-org/responsively-app/pull/364

> Version: 0.11.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

![Screen Shot 2020-08-25 at 3 16 00 PM](https://user-images.githubusercontent.com/1315054/91217764-093bc500-e6e6-11ea-9e99-9fc4126a8ef5.png)
![Screen Shot 2020-08-25 at 3 16 13 PM](https://user-images.githubusercontent.com/1315054/91217769-0b058880-e6e6-11ea-9589-ad060463769a.png)

**Comment by jjavierdguezas** [comment]
closing then
