### ISSUE TITLE
Mirror Interaction - Scroll Not Working for some websites like GitHub.com where the CSP prevents it. 

### ISSUE THREAD

**Issue by Ivl-Nunez** [responsively-org/responsively-app#860]
# 🐞 bug report

### ✍️ Description
When scrolling in any of the views, the other views do not mirror.

### 🕵🏼‍♂️ Is this a regression?
No that I am aware of.

### 🔬 Minimal Reproduction
Download via website, not brew.
Open and scroll in any view.

### 🌍 Your Environment
Macbook Pro w/ Silicon Chip M1

### 🔥 Exception or Error or Screenshot

https://www.loom.com/share/1760df64836748ed9573febd5cb1666f

**Comment by manojVivek** [comment]
Hey, thank you so much for the detailed recording. 

I took a brief look, and it looks the scroll mirroring is not entirely broken, it works for most pages. 

It fails on https://github.com because of GitHub's content security policy, which rejects the `browserSync` script that we embed to enable the scroll mirroring. 

I'll see what can be done about this.

**Comment by crbon** [comment]
I've noticed a similar issue where the scroll sync doesn't work on the site [https://maze.co/](https://maze.co/).
I'm not sure if CSP is the issue or something else.

**Comment by manojVivek** [comment]
maze.co doesn't work because of CSP as well.

**Comment by manojVivek** [comment]
Fixed in #931

**Comment by manojVivek** [comment]
The fix is live on v1.3.0, please let me know if you still face the issue after the upgrade.
